### ISSUE TITLE
feat: Read Yaml file

### ISSUE THREAD

**Issue by puneeth072003** [puneeth072003/CODESOURCERER#15]
Contents that need to be fetched
-  test-directory: string
- comments: on/off
- testing-branch: string
- testing-framework: string
- water-mark: on/off
- redis-caching: on/off

YAML file name: `codesourcerer-config.yml`

**Comment by KushalJetty** [comment]
i'll work on this

**Comment by KushalJetty** [comment]
function is added. need any improvements

**Comment by puneeth072003** [comment]
i have mentioned the changes within your PR please do those ASAP

**Comment by KushalJetty** [comment]
made changes
