### ISSUE TITLE
Fix code scanning alert - Uncontrolled data used in network request

### ISSUE THREAD

**Issue by puneeth072003** [puneeth072003/CODESOURCERER#31]
Tracking issue for:
- [ ] https://github.com/puneeth072003/CODESOURCERER/security/code-scanning/3
- [ ] https://github.com/puneeth072003/CODESOURCERER/security/code-scanning/4

**Comment by puneeth072003** [comment]
@soorya-u can you work on this

**Comment by soorya-u** [comment]
I'll look into it
